services:
  web:
    restart: always
    environment:
      # Behind TLS termination (Caddy), trust proxy headers.
      FG_PROXY_HEADERS: "1"
      # Explicitly set this; avoid '*' unless you're certain only the proxy can reach the app.
      FG_FORWARDED_ALLOW_IPS: "${FG_FORWARDED_ALLOW_IPS:?set FG_FORWARDED_ALLOW_IPS in .env}"

  worker:
    restart: always

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Set this to your public hostname (e.g. fieldgrade.example.com)
      FIELDGRADE_DOMAIN: "${FIELDGRADE_DOMAIN:?set FIELDGRADE_DOMAIN in .env}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  caddy_data: {}
  caddy_config: {}
